name: scaffold-infrastructure
run-name: ${{ github.actor }}

on: 
    push:
      paths:
        - "infrastructure/*"
    workflow_dispatch:
        inputs:
            environment:
                description: 'Environment, this will be used as workspace'
                required: true
                default: 'dev'
                type: choice
                options:
                    - dev
                    - staging
                    - prod
            action:
              description: "Chose between create or destroy the environment"
              required: true
              type: choice
              options:
                - create # Only for visual, nothing really doing much :)
                - destroy
                    
env:
    ROLE_TO_ASSUME: arn:aws:iam::760772947412:role/github-actions/gh-oidc
    AWS_REGION: us-east-1


permissions:
    id-token: write
    contents: read

jobs:
    scaffold:
      uses: ./.github/workflows/terraform.yml
      with:
        apply: ${{ github.branch == 'main' }}
        destroy: ${{ inputs.action == 'destroy' }}
        fmt-check: false
        workspace: ${{ inputs.workspace  }}
        working-dir: infrastructure

