name: scaffold-cron
run-name: ${{ github.actor }}

on:
  schedule:
    - cron: "00 01 * * 1-5"   # Run on Weekdays at 1AM UTC

permissions:
  id-token: write
  contents: read

jobs:
  scheduled-create:
    strategy:
      matrix:
        environment: ["dev"]
    uses: ./.github/workflows/terraform.yml
    with:
      apply: true
      workspace: ${{ matrix.environment }}
      working-dir: infrastructure/scaffold
      role-to-assume: arn:aws:iam::169740125934:role/github-actions/gh-oidc