name: terraform-init
on: 
  workflow_call:
    inputs:
      fmt-check:
        default: false
        description: "Wheter or not check the formatting and error out"
        type: boolean
jobs:
  terraform-init:
    runs-on: ubuntu-latest
    steps:
      - name: terraform-fmt
        id: fmt
        if: inputs.fmt-check == 'true'
        run: terraform fmt -check
      - name: terraform-init
        id: init
        run: terraform init
      - name: terraform-validate
        id: validate
        run: terraform validate -no-color
