name: vanish
run-name: "Destroying in case we forgot"
on:
  schedule:
    - cron: "0 05 * * *"  # Every 5AM UTC Mon-Fri

env: 
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  scheduled-destroy:
    strategy:
      matrix:
        environment: ["dev", "staging", "prod"]
    uses: ./.github/workflows/terraform.yml
    with:
      apply: true
      destroy: true
      fmt-check: false
      workspace: ${{ matrix.environment }}
      working-dir: infrastructure/scaffold
      role-to-assume: arn:aws:iam::169740125934:role/github-actions/gh-oidc
