name: vanish
run-name: "Destroying in case we forgot"
on:
  # push: # Use for testing, remove afterwards
  schedule:
    - cron: "0 23 * * *"

env: 
  ROLE_TO_ASSUME: arn:aws:iam::760772947412:role/github-actions/gh-oidc
  AWS_REGION: us-east-1

permissions:
  id-token: write
  contents: read

jobs:
  scheduled-destroy:
    strategy:
      matrix:
        environment: ["dev", "staging", "prod"]
    uses: ./.github/workflows/terraform.yml
    with:
      apply: true
      destroy: true
      fmt-check: false
      workspace: ${{ matrix.environment }}
      working-dir: infrastructure/scaffold
      role-to-assume: arn:aws:iam::760772947412:role/github-actions/gh-oidc
